name: PR Lifecycle Events

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pr-events:
    runs-on: ubuntu-latest

    steps:
      - name: Print PR Event Type
        run: echo "Event type -> ${{ github.event.action }}"

      - name: Print PR Title
        run: echo "PR Title -> ${{ github.event.pull_request.title }}"

      - name: Print PR Author
        run: echo "PR Author -> ${{ github.event.pull_request.user.login }}"

      - name: Print Source and Target Branch
        run: |
          echo "Source Branch -> ${{ github.head_ref }}"
          echo "Target Branch -> ${{ github.base_ref }}"

      - name: Run Only If PR Was Merged
        if: ${{ github.event.pull_request.merged == true }}
        run: echo "PR was merged successfully"