name: Scheduled Tasks

on:
  schedule:
    - cron: '30 2 * * 1'
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Trigger Schedule
        run: echo "Triggered by schedule -> ${{ github.event.schedule }}"

      - name: Health Check
        run: |
          URL="https://example.com"

          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)

          echo "Response code: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Health check failed"
            exit 1
          fi